name: Update & build blocklists
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
      - "**/build.yml"
      - "**/*.sh"
  schedule:
    - cron: "30 16 * * 5"
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.1
      - name: Set variables
        run: |
          echo "RELEASE_NAME=$(date +%Y)d$(printf '%02g' $(($(date +%m)*3+$(date +%d)/10)))z" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y)d$(printf '%02g' $(($(date +%m)*3+$(date +%d)/10)))z" >> $GITHUB_ENV
        shell: bash
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Build dlc.dat file
        run: |
          bash updater.sh
          go run ./ --outputdir=./
      - name: Generate dlc.dat sha256 hash
        run: |
          sha256sum dlc.dat > dlc.dat.sha256sum
      - name: Show folder structure
        run: |
          sudo apt install tree -y
          tree -ifl .
      - name: "Rewrite release"
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          #artifacts: "pages-build.tar.gz,pages-build-gz.tar,pages-build-br.tar,build-time.txt"
          artifacts: "dlc.dat,dlc.dat.sha256sum"
          allowUpdates: true
          artifactErrorsFailBuild: true
          makeLatest: true
          prerelease: false
          removeArtifacts: true
          replacesArtifacts: true
          name: ${{ env.RELEASE_NAME }}
          tag: ${{ env.TAG_NAME }}